### ISSUE TITLE
iPad compatibility

### ISSUE THREAD

**Issue by kasnder** [ubapsi/appchk-app#1]
Trying to run your app on my iPad, I noticed that you do not currently seem to be targeting iPhones only. The app doesn’t run in fullscreen.

**Comment by ghost** [comment]
Yes, the app was developed for iPhone only (and interestingly it runs on M1 Macs too). I'll have a look at what it takes to adapt it to an iPad screen. Not sure what I should display at the additional screen space though. Just the 3–4 layers of navigation seems a bit unnecessary. If you have a specific idea for the layout / UI elements don't hesitate to share it :)

**Comment by kasnder** [comment]
Just thought there might be a quick fix! Obviously, this is not a priority.

**Comment by ghost** [comment]
Yeah, just tested setting the checkmark only. Looks good enough without any further modifications. At least not in the immediate future. Let me know if this version has any unintentional bugs. Shouldn't be since it was just a checkmark but you never know …

**Comment by kasnder** [comment]
Looks great on my device! Thanks.
